### ISSUE TITLE
Error to install wav2letter

### ISSUE THREAD

**Issue by skgusrb12** [flashlight/wav2letter#990]
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
    ERROR: Command errored out with exit status 1:
     command: /home/hmi/anaconda3/envs/pororo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/hmi/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/home/hmi/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/hmi/wav2letter/bindings/python/
    Complete output (88 lines):
    running develop
    running egg_info
    creating wav2letter.egg-info
    writing wav2letter.egg-info/PKG-INFO
    writing dependency_links to wav2letter.egg-info/dependency_links.txt
    writing top-level names to wav2letter.egg-info/top_level.txt
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
    reading manifest file 'wav2letter.egg-info/SOURCES.txt'
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- CUDA found (library: /usr/local/cuda-10.2/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda-10.2/include)
    -- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_70,code=compute_70-gencodearch=compute_75,code=compute_75
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Checking for [Accelerate]
    -- Checking for [vecLib]
    -- Checking for [cblas - atlas]
    -- Checking for [openblas]
    -- Checking for [cblas]
    -- Checking for [blas]
    CMake Error at cmake/FindCBLAS.cmake:334 (MESSAGE):
      CBLAS library not found.  Please specify library location
    Call Stack (most recent call first):
      src/libraries/feature/CMakeLists.txt:10 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/hmi/wav2letter/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/home/hmi/wav2letter/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/hmi/wav2letter/bindings/python/setup.py", line 95, in <module>
        setup(
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/hmi/wav2letter/bindings/python/setup.py", line 48, in run
        self.build_extensions()
      File "/home/hmi/wav2letter/bindings/python/setup.py", line 87, in build_extensions
        subprocess.check_call(
      File "/home/hmi/anaconda3/envs/pororo/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/hmi/wav2letter', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/hmi/wav2letter/bindings/python/wav2letter', '-DPYTHON_EXECUTABLE=/home/hmi/anaconda3/envs/pororo/bin/python', '-DW2L_BUILD_LIBRARIES_ONLY=ON', '-DW2L_BUILD_FOR_PYTHON=ON', '-DW2L_LIBRARIES_USE_CUDA=ON', '-DW2L_LIBRARIES_USE_KENLM=ON', '-DW2L_LIBRARIES_USE_MKL=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/hmi/anaconda3/envs/pororo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/hmi/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/home/hmi/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
===========================================================================

I am installing wav2letter to run wav2vec, but I am facing above error.

** In my shell: 
  rm -rf wav2letter
  git clone -b v0.2 https://github.com/facebookresearch/wav2letter.git
  cd wav2letter/bindings/python
  export KENLM_ROOT_DIR=$ABSOLUTE_PATH'/kenlm/'
  rm -rf build
  pip install -e .
  cd ../../..

** In my environment: 
  CUDA : 10.2
  pytorch :  1.6.0
  packaging : 19.1

**Comment by tlikhomanenko** [comment]
As listed here https://github.com/flashlight/wav2letter/wiki/Building-Python-bindings you need to have Atlas or OpenBlas dependency installed.

**Comment by skgusrb12** [comment]
Thank you for you reply.

In my shell script, I worked as follows:  
apt-get install -y libsndfile1-dev libatlas-base-dev libopenblas-dev libfftw3-dev libgflags-dev libgoogle-glog-dev

But, I am still facing the same error.

**Comment by tlikhomanenko** [comment]
My guess it is trying to use MKL version and you didn't install it. Could you set `export USE_MKL=OFF` and then reinstall w2l?
