### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by at3e** [flashlight/wav2letter#999]
### Question
I have tried the installation instructions [here](https://github.com/flashlight/wav2letter/wiki/Building-Python-bindingsl) , with USE_CUDA=0. However, It still gives the following error:
`running install
running bdist_egg
running egg_info
writing wav2letter.egg-info/PKG-INFO
writing dependency_links to wav2letter.egg-info/dependency_links.txt
writing top-level names to wav2letter.egg-info/top_level.txt
reading manifest file 'wav2letter.egg-info/SOURCES.txt'
writing manifest file 'wav2letter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /home/at3ee/anaconda3/envs/py37/bin/x86_64-conda_cos6-linux-gnu-cc
-- Check for working C compiler: /home/at3ee/anaconda3/envs/py37/bin/x86_64-conda_cos6-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/at3ee/anaconda3/envs/py37/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: /home/at3ee/anaconda3/envs/py37/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Checking for [openblas]
-- Checking for [cblas]
-- Checking for [blas]
CMake Error at cmake/FindCBLAS.cmake:334 (MESSAGE):
  CBLAS library not found.  Please specify library location
Call Stack (most recent call first):
  src/libraries/feature/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/at3ee/wav2letter/bindings/python/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 175, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 161, in call_command
    self.run_command(cmdname)
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extensions()
  File "setup.py", line 88, in build_extensions
    ["cmake", sourcedir] + cmake_args, cwd=self.build_temp, env=env
  File "/home/at3ee/anaconda3/envs/py37/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/at3ee/wav2letter', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/at3ee/wav2letter/bindings/python/wav2letter', '-DPYTHON_EXECUTABLE=/home/at3ee/anaconda3/envs/py37/bin/python', '-DW2L_BUILD_LIBRARIES_ONLY=ON', '-DW2L_BUILD_FOR_PYTHON=ON', '-DW2L_LIBRARIES_USE_CUDA=OFF', '-DW2L_LIBRARIES_USE_KENLM=ON', '-DW2L_LIBRARIES_USE_MKL=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
`

Could you please point out where I am going wrong?

**Comment by stefansjs** [comment]
I'm getting this same "CBLAS library not found" error when trying to build in a conda environment. I've tried setting `-DCMAKE_PREFIX_PATH=$CONDA_PREFIX` and cmake still won't find libcblas. Has anybody successfully installed this in a conda environment?

FYI these instructions are linked to in https://github.com/asappresearch/slue-toolkit?tab=readme-ov-file
